apiVersion: opsos/v1
kind: Configuration
metadata:
  name: opsos-test-config
  description: OPSOS Test Configuration
spec:
  base_path: .
  stacks:
    base_path: stacks
    included_paths:
      - "orgs/**/*"
    excluded_paths:
      - "**/_defaults.yaml"
    name_pattern: "{{.tenant}}-{{.environment}}-{{.stage}}"
  logs:
    level: debug
  helmfile:
    base_path: components/helmfile
    kubeconfig_path: /dev/shm
  terraform:
    base_path: components/terraform
    apply_auto_approve: false
    deploy_run_init: true
    init_run_reconfigure: true
    auto_generate_backend_file: false
  kind:
    cluster_name_pattern: "{{.namespace}}-{{.tenant}}-{{.environment}}-{{.stage}}"

